name: MANUAL Release to Docker Hub

on:
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  fetch-tags: true

            - name: 'Set up QEMU'
              uses: docker/setup-qemu-action@v3.0.0

            - name: 'Set up Docker Buildx'
              uses: docker/setup-buildx-action@v3.0.0

            - name: 'Get Previous tag'
              id: get_tag
              uses: 'WyriHaximus/github-action-get-previous-tag@v1'
              with:
                  fallback: latest # Optional fallback tag to use when no tag can be found

            - name: Build and push Docker image
              id: docker_build
              uses: docker/build-push-action@v5.1.0
              with:
                  platforms: linux/amd64,linux/arm64
                  build-args: |
                      chash=${{ github.sha }}
                      version=${{ steps.get_tag.outputs.tag || 'latest' }}
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.get_release.outputs.tag || 'latest' }}, ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:latest

            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}
